# Generated by Django 3.2.25 on 2025-07-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='images',
            new_name='image',
        ),
    ]
